version: '3.8'

services:

  db:
    build:
      context: ./db
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/mysql
    networks:
      - main

  php:
    build:
      args:
        user: jack
        uid: 1000
      context: ./php
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ./src:/var/www
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - main

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./src:/var/www
    depends_on:
      - php
    ports:
      - 80:80
    networks:
      - main

networks:
  main:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28